config/routes.rb
Rails.application.routes.draw do
  resources :tasks
  resources :projects
  resources :user_roles
  resources :roles
  devise_for :users
  get 'home/index'

  root 'home#index'

end

app/views/shareds/_navbar.html.erb
<div class="container">
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%if user_signed_in?%>
          <a class="navbar-brand" href="#"><%= "#{rol_user(current_user.id)} #{current_user.email}"%></a>
          <%else%>
          <a class="navbar-brand" href="#">Administrador de tareas</a>          
        <% end %>        
      </div>
      <%if user_signed_in?%>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li>
              <%= link_to 'Proyectos', projects_path %>
            </li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li>
              <%= link_to 'Salir',  destroy_user_session_path, :method => :delete%>
            </li>
          </ul>
        </div>
      <%else%>
          <ul class="nav navbar-nav navbar-right">
            <li>
              <a href="/users/sign_in">Ingresar</a>
            </li>
            <li>
              <a href="/users/sign_up">Registrarme</a>
            </li>            
          </ul>
      <% end %>
    </div>
  </nav>  
</div>