config/routes.rb
Rails.application.routes.draw do
  resources :tasks
  resources :projects
  resources :user_roles
  resources :roles
  devise_for :users
  get 'home/index'

  root 'home#index'

end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :user
  has_many :tasks
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  include UserHelper
  before_action :authenticate_user!
  # GET /projects
  # GET /projects.json
  def index
    if administrator(current_user.id)
      @projects = Project.where(:user_id => current_user.id)
    else
      @projects = Project.where(:id => Task.where(:user_id => current_user.id).select(:project_id))
    end    
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit 
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)
    @project.start_project = DateTime.strptime("#{project_params[:start_project].split('/')[2].split(' ')[0]}#{project_params[:start_project].split('/')[0]}#{project_params[:start_project].split('/')[1]}","%Y%m%d")
    @project.end_project = DateTime.strptime("#{project_params[:end_project].split('/')[2].split(' ')[0]}#{project_params[:end_project].split('/')[0]}#{project_params[:end_project].split('/')[1]}","%Y%m%d")
    respond_to do |format|
      if @project.save
        format.html { redirect_to projects_path, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|      
      if project_params[:start_project] != ""
        @project.update(:start_project => DateTime.strptime("#{project_params[:start_project].split('/')[2].split(' ')[0]}#{project_params[:start_project].split('/')[0]}#{project_params[:start_project].split('/')[1]}","%Y%m%d"))        
      end
      if project_params[:end_project] != ""
        @project.update(:end_project => DateTime.strptime("#{project_params[:end_project].split('/')[2].split(' ')[0]}#{project_params[:end_project].split('/')[0]}#{project_params[:end_project].split('/')[1]}","%Y%m%d"))        
      end      
      if @project.update(project_params)
        format.html { redirect_to projects_path, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end    
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :user_id, :start_project, :end_project, :description)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
	def have_task(project_id)
		resultado = false
		tasks = Task.where(:project_id => project_id)
		if tasks.count > 0
			resultado = true
		end
		return( resultado)
	end
end

app/views/projects/_form.html.erb
<div class="container">
  <%= form_for(@project, :html => {:class => 'form-app'}) do |f| %>
      <%= f.hidden_field :user_id, :value => current_user.id %>
      <div class="form-group">
        <label for="inputEmail" class="sr-only">Email</label>
        <%= f.text_field :name, autofocus: true, :type => 'text', :id => 'inputEmail', :class => 'form-control', :placeholder => 'Nombre del proyecto', :required => 'Nombre requerido' %>        
      </div>
      <div class="form-group">
        <input type="text" class="form-control" value="<%= current_user.email %>" disabled></input>
      </div>
      
      <div class="form-group">
          <p class="form-group">Fecha de inicio actual: <%= @project.start_project%></p>  
          <div class='input-group date' id='start_project'>
              <%= f.text_field :start_project, :id => 'start_project', :class => 'datepicker form-control', :placeholder => 'Fecha de inicio del proyecto' %>
              <span class="input-group-addon">
                  <span class="glyphicon glyphicon-calendar"></span>
              </span>
          </div>
      </div>
      <div class="form-group">
        <p class="form-group">Fecha de finalzación actual: <%= @project.end_project%></p>  
          <div class='input-group date' id='end_project'>
              <%= f.text_field :end_project, :class => 'datepicker form-control', :placeholder => 'Fecha de finalzación del proyecto' %>
              <span class="input-group-addon">
                  <span class="glyphicon glyphicon-calendar"></span>
              </span>
          </div>
      </div>
      <div class="form-group">
        <h3 for="comment">Descripción:</h3>
        <%= f.text_area :description, :size => "0x10", autofocus: true, :type => 'text', :id => 'description', :class => 'form-control', :placeholder => 'Breve Descripcioón del proyecto', :required => 'Nombre requerido'%>        
      </div>

      <%= f.submit "Crear proyecto", :class => 'btn btn-success' %>
  <% end %>
</div>


<script type="text/javascript">
  $(function () {
    $('#start_project').datetimepicker();
    $('#end_project').datetimepicker();
  });
  $( document ).ready(function() {
    
});
</script>

app/views/projects/edit.html.erb
<div class="container">
	<h1 style="text-align: center;">Editar Proyecto</h1>	
	<hr>
</div>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<div class="container">
  <h1 style="text-align: center;">Mis proyectos</h1> 
  <hr>
</div>
<div class="container">
  <% if @projects.count > 0%>
    <table class="table">
      <thead>
        <tr>
          <th>Nombre proyecto</th>
          <th>Admin</th>
          <th>Descripción</th>
          <th>Fecha inicio</th>
          <th>Fecha finalización</th>
          <th>Activo ?</th>
          <%if administrator(current_user.id) %>        
            <th></th>
            <th></th>          
            <th>Crear tarea</th>        
          <%end%>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @projects.each do |project| %>
        <tr>
          <th>
            <%= project.name %>
          </th>
          <th>
            <%= project.user.email %>
          </th>
          <th>
            <%= project.description[0, 30]%>
          </th>
          <th>
            <%= project.start_project %>
          </th>
          <th>
            <%= project.end_project %>
          </th>
          <th style="text-align: center;">
              <% if project.active == true%>  
                <span class="glyphicon glyphicon-ok" aria-hidden="true"></span>
              <% else %> 
                <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>                         
              <% end %>              
          </th>
          <%if administrator(current_user.id) %>
            <th>
              <%= link_to edit_project_path(project) do %>
                  <i class="glyphicon glyphicon-pencil"></i>
              <% end %>          
            </th>
            <th>
              <%= link_to project, method: :delete, data: { confirm: 'Are you sure?' } do %>
                  <i class="glyphicon glyphicon-trash"></i>
              <% end %>                              
            </th>
            <th style="text-align: center;">
              <%= link_to new_task_path(:project_id => project.id) do%>
                  <i class="glyphicon glyphicon-list-alt"></i>
              <% end %>                                        
            </th>
          <%end%>        
            <th>
              <%= link_to tasks_path(:project_id => project.id) do %>
                  <i class="glyphicon glyphicon-search"></i>
              <% end %>                    
            </th>          
        </tr>
        <% end %>
      </tbody>
    </table>   
  <% else %>
    <div class="alert alert-danger" role="alert">
      <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
      No se le han asignado tareas a ningún proyecto
    </div>  
  <% end%>
  <% if administrator(current_user.id)%>
    <%= link_to 'New Project', new_project_path, :class => 'btn btn-success' %> 
  <%end%>
  
</div>

app/views/projects/new.html.erb
<div class="container">
	<h1 style="text-align: center;">Crear nuevo proyecto</h1>	
	<hr>
</div>



<%= render 'form' %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @project.name %>
</p>

<p>
  <strong>User:</strong>
  <%= @project.user %>
</p>

<p>
  <strong>Start project:</strong>
  <%= @project.start_project %>
</p>

<p>
  <strong>End project:</strong>
  <%= @project.end_project %>
</p>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>